### ISSUE TITLE
Beat Saber: Failing to sync after deleting song

### ISSUE THREAD

**Issue by olemartinorg** [the-expanse/SideQuest#115]
Hi! First of all, thanks for this fantastic software!

I wanted to buy the full Imagine Dragons song pack, so I went ahead and removed some Imagine Dragons songs from my custom ones. I did so by going to the Beast Saber tab in SideQuest and removing the songs from there. They no longer show up in my custom levels list.

However, when I try to sync the songs to the Quest, I get this error:

    System.ArgumentException: An item with the same key has already been added. Key: assets/bin/Data/14040-15153_WolfgangLohrandMaskeradeHittheRoadJack.ogg

    at System.Collections.Generic.Dictionary2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
    at Ionic.Zip.ZipFile.InternalAddEntry(String name, ZipEntry entry)
    at Ionic.Zip.ZipFile._InternalAddEntry(ZipEntry ze)
    at LibSaberPatch.Apk.CopyFileInto(String sourceFilePath, String destEntryPath)
        in C:\projects\QuestSaberPatch\LibSaberPatch\Apk.cs:line 118
    at LibSaberPatch.Apk.Transaction.ApplyTo(Apk apk)
        in C:\projects\QuestSaberPatch\LibSaberPatch\Apk.cs:line 225
    at jsonApp.Program.Install(Apk apk, SerializedAssets assets, HashSet`1 toInstall, InvocationResult res, Dictionary2 levels)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 214
    at jsonApp.Program.SyncLevels(Apk apk, SerializedAssets mainAssets, Invocation inv, InvocationResult res)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 164
    jsonApp.Program.RunInvocation(Invocation inv)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 87

Seems to me that the song is still stuck in limbo where it is expected to exists, but doesn't anymore.

Also, some of the songs I removed (not all, it seems?) caused SideQuest to complain in the bottom bar about the folder existing, but being empty. I just removed the empty folders it complained about from my custom songs folder, and SideQuest complains no more.

**Comment by avluis** [comment]
It seems as if the apk file that's already installed may not be allowing you to remove whats already there.
Have you tried uninstalling Beat Saver, re-downloading and re-applying the patch (as if a new patch/game update is up)?

**Comment by olemartinorg** [comment]
I did this right after upgrading to 1.1.0, so I already had a clean new install. I did a 'redownload patcher' now, backed up a new master, and it still fails with the same error message. Not sure what I need to delete in order for the Thunder song to go away. Right now it's not possible to re-download it either, so I can't work around it that way.

**Comment by avluis** [comment]
Can you make sure that this folder `14040-15153` doesn't exist in the bsaber directory (where the songs are downloaded to) and that there are not two copies of the song included (check the directory itself).

That seems to be what it's complaining about -- otherwise I would move all the songs out into a safe location, sync a few songs (by copying the respective directories back in) and see if the error goes away.

**Comment by olemartinorg** [comment]
I had a look around, and it seems I actually pasted the wrong error message! Sorry about that. I got the error about `14040-15153` as well, but that usually goes away with some refreshing and manual massaging (read: re-downloading the patcher and resetting the master). The folder _is_ in my `bsaber` folder, the song is in `My Levels` and a level pack.

The one I'm really stuck at (which is why I wrote about Imagine Dragons in the first comment) is this:

    System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\MyUserName\AppData\Roaming\SideQuest\bsaber\18852-20493\Thunder\info.dat'.
    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
    at System.IO.File.ReadAllText(String path)
    at LibSaberPatch.JsonLevel.LoadFromFolder(String levelFolderPath)
        in C:\projects\QuestSaberPatch\LibSaberPatch\JSONTypes.cs:line 122
    at jsonApp.Program.Install(Apk apk, SerializedAssets assets, HashSet`1 toInstall, InvocationResult res, Dictionary`2 levels)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 199
    at jsonApp.Program.SyncLevels(Apk apk, SerializedAssets mainAssets, Invocation inv, InvocationResult res)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 164
    at jsonApp.Program.RunInvocation(Invocation inv)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 87

And the scenario is now:

- I can confirm that the folder `18852-20493` does not exist (just as the error message implies)
- The level `Thunder` is not in the list of `My Levels`
- The level `Thunder` is not in any level pack

**Comment by olemartinorg** [comment]
Ok, I made some progress! `14040-15153` is the first of my custom songs, that's why it's failing each time. It seems that the error about Thunder not existing stops the patcher, and the patcher doesn't clean up after itself so the next time I run the patcher (if I don't redownload it) it will stop at the first song since it is already added to the assets.

Anyway, what I did now was redownload the `18852-20493` song from bsaber.com in my regular browser, and place it manually how it was in the `bsaber` directory. I now get past that error and it now complains about `8119-8175`, Believer, which I also deleted via the button inside Beast Saber embedded in SideQuest.

I've learned my lesson, don't delete from Beast Saber inside SideQuest yet, as it doesn't seem to remove all the metadata. I'll have a look into restoring my `bsaber` folder to a working state to get this working again, and try to remove the songs via the `My Levels` tab instead.

**Comment by shaneharris** [comment]
this should be fixed in the latest version 0.3.3!

**Comment by olemartinorg** [comment]
I can confirm that the above error happens no longer, but the overall bug report of "Failing to sync after deleting song" is not fixed quite yet.

I have some songs from the Anniversary Team that I downloaded earlier (older format, with decimal IDs). Deleting them now breaks syncing for me. I've removed these songs from both `My Levels` AND from the level packs (why? shouldn't removing them from `My Levels` remove them from both?), and now I'm getting this error every other time I try to sync (the other times i get the autofix dialog):

    System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\MyUser\AppData\Roaming\SideQuest\bsaber\17483-19015\info.dat'.
    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
    at System.IO.File.ReadAllText(String path)
    at LibSaberPatch.JsonLevel.LoadFromFolder(String levelFolderPath)
        in C:\projects\QuestSaberPatch\LibSaberPatch\JSONTypes.cs:line 122
    at jsonApp.Program.Install(Apk apk, SerializedAssets assets, HashSet`1 toInstall, InvocationResult res, Dictionary`2 levels)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 199
    at jsonApp.Program.SyncLevels(Apk apk, SerializedAssets mainAssets, Invocation inv, InvocationResult res)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 164
    at jsonApp.Program.RunInvocation(Invocation inv)
        in C:\projects\QuestSaberPatch\jsonApp2\Program.cs:line 87

**Comment by olemartinorg** [comment]
The new option to clean up my packs finally fixes my problems! Thanks @shaneharris!
